# Generated by Django 5.0.7 on 2024-08-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockcomment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
