# Generated by Django 5.0.7 on 2024-08-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("pass1", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                ("gender", models.IntegerField(default=0)),
                ("tel", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PageAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_time", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("page_url", models.CharField(max_length=255)),
                ("user_id", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
