# Generated by Django 5.0.7 on 2024-08-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('page_url', models.CharField(max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
